import type { AriaAttributes } from './aria';
import type { CSSAttributes } from './css';
import type { DOMEventAttributes } from './dom';

export interface SVGAttributes<E extends SVGElement> extends AriaAttributes, CSSAttributes, DOMEventAttributes<E> {
	innerHTML?: string

	/**
	 * SVG Styling Attributes
	 * @see https://www.w3.org/TR/SVG/styling.html#ElementSpecificStyling
	 */

	color?: string
	height?: number
	id?: string
	lang?: string
	max?: number
	media?: string
	method?: string
	min?: number
	name?: string
	target?: string
	type?: string
	width?: number

	// Other HTML properties supported by SVG elements in browsers
	role?: string
	tabIndex?: number

	// SVG Specific attributes
	'accent-height'?: number
	accumulate?: 'none' | 'sum'
	additive?: 'replace' | 'sum'
	'alignment-baseline'?:
	  | 'auto'
	  | 'baseline'
	  | 'before-edge'
	  | 'text-before-edge'
	  | 'middle'
	  | 'central'
	  | 'after-edge'
	  | 'text-after-edge'
	  | 'ideographic'
	  | 'alphabetic'
	  | 'hanging'
	  | 'mathematical'
	  | 'inherit'
	allowReorder?: 'no' | 'yes'
	alphabetic?: number
	amplitude?: number
	'arabic-form'?: 'initial' | 'medial' | 'terminal' | 'isolated'
	ascent?: number
	attributeName?: string
	attributeType?: string
	autoReverse?: number
	azimuth?: number
	baseFrequency?: number
	'baseline-shift'?: number
	baseProfile?: number
	bbox?: number
	begin?: number
	bias?: number
	by?: number
	calcMode?: number
	'cap-height'?: number
	clip?: number
	'clip-path'?: string
	clipPathUnits?: number
	'clip-rule'?: number
	'color-interpolation'?: number
	'color-interpolation-filters'?: 'auto' | 'sRGB' | 'linearRGB' | 'inherit'
	'color-profile'?: number
	'color-rendering'?: number
	contentScriptType?: number
	contentStyleType?: number
	cursor?: number
	cx?: number
	cy?: number
	d?: string
	decelerate?: number
	descent?: number
	diffuseConstant?: number
	direction?: number
	display?: number
	divisor?: number
	'dominant-baseline'?: number
	dur?: number
	dx?: number
	dy?: number
	edgeMode?: number
	elevation?: number
	'enable-background'?: number
	end?: number
	exponent?: number
	externalResourcesRequired?: number
	fill?: string
	'fill-opacity'?: number
	'fill-rule'?: 'nonzero' | 'evenodd' | 'inherit'
	filter?: string
	filterRes?: number
	filterUnits?: number
	'flood-color'?: number
	'flood-opacity'?: number
	focusable?: number
	'font-family'?: string
	'font-size'?: number
	'font-size-adjust'?: number
	'font-stretch'?: number
	'font-style'?: number
	'font-variant'?: number
	'font-weight'?: number
	format?: number
	from?: number
	fx?: number
	fy?: number
	g1?: number
	g2?: number
	'glyph-name'?: number
	'glyph-orientation-horizontal'?: number
	'glyph-orientation-vertical'?: number
	glyphRef?: number
	gradientTransform?: string
	gradientUnits?: string
	hanging?: number
	'horiz-adv-x'?: number
	'horiz-origin-x'?: number
	href?: string
	ideographic?: number
	'image-rendering'?: number
	in2?: number
	in?: string
	intercept?: number
	k1?: number
	k2?: number
	k3?: number
	k4?: number
	k?: number
	kernelMatrix?: number
	kernelUnitLength?: number
	kerning?: number
	keyPoints?: number
	keySplines?: number
	keyTimes?: number
	lengthAdjust?: number
	'letter-spacing'?: number
	'lighting-color'?: number
	limitingConeAngle?: number
	local?: number
	'marker-end'?: string
	markerHeight?: number
	'marker-mid'?: string
	'marker-start'?: string
	markerUnits?: number
	markerWidth?: number
	mask?: string
	maskContentUnits?: number
	maskUnits?: number
	mathematical?: number
	mode?: number
	numOctaves?: number
	offset?: number
	opacity?: number
	operator?: number
	order?: number
	orient?: number
	orientation?: number
	origin?: number
	overflow?: number
	'overline-position'?: number
	'overline-thickness'?: number
	'paint-order'?: number
	'panose-1'?: number
	pathLength?: number
	patternContentUnits?: string
	patternTransform?: number
	patternUnits?: string
	'pointer-events'?: number
	points?: string
	pointsAtX?: number
	pointsAtY?: number
	pointsAtZ?: number
	preserveAlpha?: number
	preserveAspectRatio?: string
	primitiveUnits?: number
	r?: number
	radius?: number
	refX?: number
	refY?: number
	renderingIntent?: number
	repeatCount?: number
	repeatDur?: number
	requiredExtensions?: number
	requiredFeatures?: number
	restart?: number
	result?: string
	rotate?: number
	rx?: number
	ry?: number
	scale?: number
	seed?: number
	'shape-rendering'?: number
	slope?: number
	spacing?: number
	specularConstant?: number
	specularExponent?: number
	speed?: number
	spreadMethod?: string
	startOffset?: number
	stdDeviation?: number
	stemh?: number
	stemv?: number
	stitchTiles?: number
	'stop-color'?: string
	'stop-opacity'?: number
	'strikethrough-position'?: number
	'strikethrough-thickness'?: number
	string?: number
	stroke?: string
	'stroke-dasharray'?: number
	'stroke-dashoffset'?: number
	'stroke-linecap'?: 'butt' | 'round' | 'square' | 'inherit'
	'stroke-linejoin'?: 'miter' | 'round' | 'bevel' | 'inherit'
	'stroke-miterlimit'?: number
	'stroke-opacity'?: number
	'stroke-width'?: number
	surfaceScale?: number
	systemLanguage?: number
	tableValues?: number
	targetX?: number
	targetY?: number
	'text-anchor'?: string
	'text-decoration'?: number
	textLength?: number
	'text-rendering'?: number
	to?: number
	transform?: string
	u1?: number
	u2?: number
	'underline-position'?: number
	'underline-thickness'?: number
	unicode?: number
	'unicode-bidi'?: number
	'unicode-range'?: number
	'unitsPer-em'?: number
	'v-alphabetic'?: number
	values?: string
	'vector-effect'?: number
	version?: string
	'vert-adv-y'?: number
	'vert-origin-x'?: number
	'vert-origin-y'?: number
	'v-hanging'?: number
	'v-ideographic'?: number
	viewBox?: string
	viewTarget?: number
	visibility?: number
	'v-mathematical'?: number
	widths?: number
	'word-spacing'?: number
	'writing-mode'?: number
	x1?: number
	x2?: number
	x?: number
	xChannelSelector?: string
	'x-height'?: number
	xlinkActuate?: string
	xlinkArcrole?: string
	xlinkHref?: string
	xlinkRole?: string
	xlinkShow?: string
	xlinkTitle?: string
	xlinkType?: string
	xmlns?: string
	y1?: number
	y2?: number
	y?: number
	yChannelSelector?: string
	z?: number
	zoomAndPan?: string
}
