import type { AriaAttributes } from './aria';
import type { CSSAttributes } from './css';
import type { DOMEventAttributes } from './dom';

export interface SVGAttributes<E extends SVGElement>
  extends AriaAttributes,
    CSSAttributes,
    DOMEventAttributes<E> {
  innerHTML?: string;

  /**
   * SVG Styling Attributes
   * @see https://www.w3.org/TR/SVG/styling.html#ElementSpecificStyling
   */

  color?: string;
  height?: number;
  id?: string;
  lang?: string;
  max?: number;
  media?: string;
  method?: string;
  min?: number;
  name?: string;
  target?: string;
  type?: string;
  width?: number;

  // Other HTML properties supported by SVG elements in browsers
  role?: string;
  tabIndex?: number;

  // SVG Specific attributes
  accentHeight?: number;
  accumulate?: 'none' | 'sum';
  additive?: 'replace' | 'sum';
  alignmentBaseline?:
    | 'auto'
    | 'baseline'
    | 'before-edge'
    | 'text-before-edge'
    | 'middle'
    | 'central'
    | 'after-edge'
    | 'text-after-edge'
    | 'ideographic'
    | 'alphabetic'
    | 'hanging'
    | 'mathematical'
    | 'inherit';
  allowReorder?: 'no' | 'yes';
  alphabetic?: number;
  amplitude?: number;
  arabicForm?: 'initial' | 'medial' | 'terminal' | 'isolated';
  ascent?: number;
  attributeName?: string;
  attributeType?: string;
  autoReverse?: number;
  azimuth?: number;
  baseFrequency?: number;
  baselineShift?: number;
  baseProfile?: number;
  bbox?: number;
  begin?: number;
  bias?: number;
  by?: number;
  calcMode?: number;
  capHeight?: number;
  clip?: number;
  clipPath?: string;
  clipPathUnits?: number;
  clipRule?: number;
  colorInterpolation?: number;
  colorInterpolationFilters?: 'auto' | 'sRGB' | 'linearRGB' | 'inherit';
  colorProfile?: number;
  colorRendering?: number;
  contentScriptType?: number;
  contentStyleType?: number;
  cursor?: number;
  cx?: number;
  cy?: number;
  d?: string;
  decelerate?: number;
  descent?: number;
  diffuseConstant?: number;
  direction?: number;
  display?: number;
  divisor?: number;
  dominantBaseline?: number;
  dur?: number;
  dx?: number;
  dy?: number;
  edgeMode?: number;
  elevation?: number;
  enableBackground?: number;
  end?: number;
  exponent?: number;
  externalResourcesRequired?: number;
  fill?: string;
  fillOpacity?: number;
  fillRule?: 'nonzero' | 'evenodd' | 'inherit';
  filter?: string;
  filterRes?: number;
  filterUnits?: number;
  floodColor?: number;
  floodOpacity?: number;
  focusable?: number;
  fontFamily?: string;
  fontSize?: number;
  fontSizeAdjust?: number;
  fontStretch?: number;
  fontStyle?: number;
  fontVariant?: number;
  fontWeight?: number;
  format?: number;
  from?: number;
  fx?: number;
  fy?: number;
  g1?: number;
  g2?: number;
  glyphName?: number;
  glyphOrientationHorizontal?: number;
  glyphOrientationVertical?: number;
  glyphRef?: number;
  gradientTransform?: string;
  gradientUnits?: string;
  hanging?: number;
  horizAdvX?: number;
  horizOriginX?: number;
  href?: string;
  ideographic?: number;
  imageRendering?: number;
  in2?: number;
  in?: string;
  intercept?: number;
  k1?: number;
  k2?: number;
  k3?: number;
  k4?: number;
  k?: number;
  kernelMatrix?: number;
  kernelUnitLength?: number;
  kerning?: number;
  keyPoints?: number;
  keySplines?: number;
  keyTimes?: number;
  lengthAdjust?: number;
  letterSpacing?: number;
  lightingColor?: number;
  limitingConeAngle?: number;
  local?: number;
  markerEnd?: string;
  markerHeight?: number;
  markerMid?: string;
  markerStart?: string;
  markerUnits?: number;
  markerWidth?: number;
  mask?: string;
  maskContentUnits?: number;
  maskUnits?: number;
  mathematical?: number;
  mode?: number;
  numOctaves?: number;
  offset?: number;
  opacity?: number;
  operator?: number;
  order?: number;
  orient?: number;
  orientation?: number;
  origin?: number;
  overflow?: number;
  overlinePosition?: number;
  overlineThickness?: number;
  paintOrder?: number;
  panose1?: number;
  pathLength?: number;
  patternContentUnits?: string;
  patternTransform?: number;
  patternUnits?: string;
  pointerEvents?: number;
  points?: string;
  pointsAtX?: number;
  pointsAtY?: number;
  pointsAtZ?: number;
  preserveAlpha?: number;
  preserveAspectRatio?: string;
  primitiveUnits?: number;
  r?: number;
  radius?: number;
  refX?: number;
  refY?: number;
  renderingIntent?: number;
  repeatCount?: number;
  repeatDur?: number;
  requiredExtensions?: number;
  requiredFeatures?: number;
  restart?: number;
  result?: string;
  rotate?: number;
  rx?: number;
  ry?: number;
  scale?: number;
  seed?: number;
  shapeRendering?: number;
  slope?: number;
  spacing?: number;
  specularConstant?: number;
  specularExponent?: number;
  speed?: number;
  spreadMethod?: string;
  startOffset?: number;
  stdDeviation?: number;
  stemh?: number;
  stemv?: number;
  stitchTiles?: number;
  stopColor?: string;
  stopOpacity?: number;
  strikethroughPosition?: number;
  strikethroughThickness?: number;
  string?: number;
  stroke?: string;
  strokeDasharray?: number;
  strokeDashoffset?: number;
  strokeLinecap?: 'butt' | 'round' | 'square' | 'inherit';
  strokeLinejoin?: 'miter' | 'round' | 'bevel' | 'inherit';
  strokeMiterlimit?: number;
  strokeOpacity?: number;
  strokeWidth?: number;
  surfaceScale?: number;
  systemLanguage?: number;
  tableValues?: number;
  targetX?: number;
  targetY?: number;
  textAnchor?: string;
  textDecoration?: number;
  textLength?: number;
  textRendering?: number;
  to?: number;
  transform?: string;
  u1?: number;
  u2?: number;
  underlinePosition?: number;
  underlineThickness?: number;
  unicode?: number;
  unicodeBidi?: number;
  unicodeRange?: number;
  unitsPerEm?: number;
  vAlphabetic?: number;
  values?: string;
  vectorEffect?: number;
  version?: string;
  vertAdvY?: number;
  vertOriginX?: number;
  vertOriginY?: number;
  vHanging?: number;
  vIdeographic?: number;
  viewBox?: string;
  viewTarget?: number;
  visibility?: number;
  vMathematical?: number;
  widths?: number;
  wordSpacing?: number;
  writingMode?: number;
  x1?: number;
  x2?: number;
  x?: number;
  xChannelSelector?: string;
  xHeight?: number;
  xlinkActuate?: string;
  xlinkArcrole?: string;
  xlinkHref?: string;
  xlinkRole?: string;
  xlinkShow?: string;
  xlinkTitle?: string;
  xlinkType?: string;
  xmlns?: string;
  y1?: number;
  y2?: number;
  y?: number;
  yChannelSelector?: string;
  z?: number;
  zoomAndPan?: string;
}
